<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Test" nsURI="test" nsPrefix="test">
  <eClassifiers xsi:type="ecore:EClass" name="Duplicate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Duplicate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" lowerBound="2" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task"/>
</ecore:EPackage>
